name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish on version bump
    runs-on: ubuntu-latest

    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'


      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Check JReleaser config
        run: ./gradlew jreleaserConfig

      - name: Stage Package
        run: ./gradlew publish

      - name: Publish Package
        run: ./gradlew jreleaserFullRelease