name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish on version bump
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Check for version bump
        id: version-check
        run: |
          git fetch origin main --depth=2
          git diff HEAD~1 HEAD build.gradle > version_diff.txt
          echo "Has version changed:"
          cat version_diff.txt
          
          if grep -q "version *= *" version_diff.txt; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if version not bumped
        if: steps.version-check.outputs.version_changed == 'false'
        run: echo "Version not changed. Skipping publish."

      - name: Make Gradle wrapper executable
        if: steps.version-check.outputs.version_changed == 'true'
        run: chmod +x ./gradlew

      - name: Publish package
        if: steps.version-check.outputs.version_changed == 'true'
        run: ./gradlew publish

        env:
          GithubPackagesRepository_User: ${{ secrets.GithubPackagesRepository_User }}
          GithubPackagesRepository_Token: ${{ secrets.GithubPackagesRepository_Token }}
